apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-service
  namespace: bedrock-chat
  labels:
    app: bedrock-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bedrock-service
  template:
    metadata:
      labels:
        app: bedrock-service
    spec:
      containers:
      - name: bedrock-service
        image: ghcr.io/your-org/bedrock-chat-bedrock-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "us-east-1"
        startupProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
